disable_disk_cache: true
exclude:
  - static/
incremental: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"
      permalink: /blog/:slug/
      body_class: home-page